### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by mrcnski** [mattduck/gh2md#41]
```
[2023-06-01 07:57:38,192] [INFO] Initiating fetch for repo: https://github.com/mrcnski/nimbus-theme
Traceback (most recent call last):
  File "/opt/homebrew/bin/gh2md", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gh2md/gh2md.py", line 807, in main
    repo = gh.fetch_and_decode_repository(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/gh2md/gh2md.py", line 569, in fetch_and_decode_repository
    owner, repo = repo_name.split("/")
    ^^^^^^^^^^^
ValueError: too many values to unpack (expected 2)
```

I get this error when I pass in the full URL, e.g. like this:

```sh
gh2md https://github.com/mrcnski/nimbus-theme nimbus-theme --multiple-files
```

I think that github URLs should either work, or at least return a more friendly user-legible error.

I'd be happy to help with this!

**Comment by mattduck** [comment]
Yeah that's a good idea, it should be possible to implement this. You're very welcome to take it on and PR it and I can release a new version. If not then I'll take a look at some point - realistically though it won't be for a while.

**Comment by mrcnski** [comment]
Cool! To keep it simple I would do this: expect a string with a single slash in it, and if anything else is found, display an error explaining the expected format. I should be able to start on this soon.

**Comment by milahu** [comment]
> github URLs should either work

see also https://github.com/nephila/giturlparse

**Comment by geneorama** [comment]
So, does this error just mean that the issue is too big?

**Comment by mattduck** [comment]
> So, does this error just mean that the issue is too big?

No, it's a bad error message -- it means the repo name argument was expected to be in the format "$owner/$repo", but when the string was split on "/" it returned more than two parts.

I've just merged and released @mrcnski's fix for this, which will display a better error message. It's in v2.3.1.

Agree that supporting URLs would be nice.
